_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
ARCHITECTURE:
    value: srunet
CLIPNAME:
    value: ""
CRF:
    value: 22
CUDA_DEVICE:
    value: "0"
DATASET_DIR:
    value: /andromeda/datasets/BVI_DVC
DOWNSAMPLE:
    value: 1
EXPORT_DIR:
    value: ""
L0:
    value: 0.001
LAYER_MULTIPLIER:
    value: 1
MODEL_NAME:
    value: null
N_EPOCHS:
    value: 80
N_FILTERS:
    value: 64
SHOW_ONLY_HQ:
    value: false
TEST_DIR:
    value: test
TEST_INPUT_RES:
    value: 540
TEST_OUTPUT_RES:
    value: 1080
UPSCALE_FACTOR:
    value: 2
VALIDATION_FREQ:
    value: 1
VERBOSE:
    value: false
VID_PATCHES:
    value: ""
W0:
    value: 1
W1:
    value: 1
WB_NAME:
    value: sr-unet
archs:
    value:
        - srunet
        - unet
        - espcn
        - srresnet
